<?php
defined('ABSPATH') or die("No script kiddies please!");

/**
 * Plugin Name: KB - Options
 * Description: Options and homepage custom fields so that they are not lost if the theme is changed..
 * Version: 1.0
 * Author: Kirsty Burgoine
 * Author URI: http://www.kirstyburgoine.co.uk
 */

// --------------------------------------------------------------------------------------
// --------------------------------------------------------------------------------------
// Global Options for each site

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_global-options',
		'title' => 'Global Options',
		'fields' => array (
			array (
				'key' => 'field_556f05cc61c97',
				'label' => 'Top Advert',
				'name' => 'top_advert',
				'type' => 'image',
				'instructions' => 'This would be an advertising banner that displays at the top of the website. The dimensions need to be: 1170 x 110px',
				'save_format' => 'object',
				'preview_size' => 'advertising-banner',
				'library' => 'all',
			),
			array (
				'key' => 'field_556f0945a5160',
				'label' => 'Top Advert Link',
				'name' => 'top_advert_link',
				'type' => 'text',
				'instructions' => 'Paste the full URL of the website that should be linked to from this advert',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555f108e4a8ec',
				'label' => 'banner',
				'name' => 'banner',
				'type' => 'image',
				'instructions' => 'This is usually the banner for the current fair that is also used on the International University Fairs website so that people know they have come to the right place.',
				'save_format' => 'object',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_556f08100e3e2',
				'label' => 'Bottom Adverts',
				'name' => 'bottom_adverts',
				'type' => 'repeater',
				'instructions' => 'These would be the advertising banners that display at the bottom of the website and would rotate through a maximum of 3 adverts. The dimensions need to be: 1170 x 110px',
				'sub_fields' => array (
					array (
						'key' => 'field_556f08a70e3e3',
						'label' => 'Advert',
						'name' => 'advert',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'advertising-banner',
						'library' => 'all',
					),
					array (
						'key' => 'field_556f0970a5161',
						'label' => 'Advert Link',
						'name' => 'advert_link',
						'type' => 'text',
						'instructions' => 'Paste the full URL of the website that should be linked to from this advert',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => 3,
				'layout' => 'table',
				'button_label' => 'Add Banner Advert',
			),
			array (
				'key' => 'field_5379d94800ccd',
				'label' => 'Company Number',
				'name' => 'company_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53416af0a8635',
				'label' => 'Copyright Notice',
				'name' => 'copyright_notice',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53416af0a8639',
				'label' => 'Contact Telephone',
				'name' => 'contact_telephone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5341663f4e85c',
				'label' => 'Contact Email',
				'name' => 'contact_email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5341654e4e853',
				'label' => 'Facebook Page',
				'name' => 'facebook_page',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534165b44e854',
				'label' => 'Twitter Account',
				'name' => 'twitter_account',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534155b44e854',
				'label' => 'LinkedIn Account',
				'name' => 'linkedin_account',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534165da4e856',
				'label' => 'Pinterest Account',
				'name' => 'pinterest_account',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534165da4e346',
				'label' => 'Instagram Account',
				'name' => 'instagram_account',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534165f44e858',
				'label' => 'YouTube Account',
				'name' => 'youtube_account',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5341682b5f14c',
				'label' => 'Vimeo Account',
				'name' => 'vimeo_account',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534166174e85a',
				'label' => 'Google+ Page',
				'name' => 'googleplus_page',
				'type' => 'text',
				'instructions' => 'Full url for the account including http://',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_homepage-options',
		'title' => 'Homepage Options',
		'fields' => array (
			array (
				'key' => 'field_555c42e25acc9',
				'label' => 'Carousel Tagline',
				'name' => 'carousel_tagline',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54e1e886442bd',
				'label' => 'Carousel',
				'name' => 'carousel',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54e1e894442be',
						'label' => 'slide image',
						'name' => 'slide_image',
						'type' => 'image',
						'instructions' => 'Preferred size is 709 x 444',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'home-image',
						'library' => 'all',
					),

				),
				'row_min' => 1,
				'row_limit' => 5,
				'layout' => 'row',
				'button_label' => 'Add Carousel Slide',
			),
			array (
				'key' => 'field_555c43929960f',
				'label' => 'Event Dates',
				'name' => 'event_dates',
				'type' => 'taxonomy',
				'instructions' => 'Select the category of event dates to display underneath the carousel',
				'taxonomy' => 'tribe_events_cat',
				'field_type' => 'radio',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_555c36f0a1eb8',
				'label' => 'Strapline',
				'name' => 'strapline',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_555c6c8f0fa1e',
				'label' => 'Exhibiting Box',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_555c6cc50fa1f',
				'label' => 'Exhibiting Image',
				'name' => 'image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_555c6d3e0fa20',
				'label' => 'Exhibiting Title',
				'name' => 'exhibiting_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555c6d4e0fa21',
				'label' => 'Exhibiting Text',
				'name' => 'exhibiting_text',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_555c6d610fa22',
				'label' => 'Exhibiting Link To Page?',
				'name' => 'exhibiting_link_to_page',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_555c6d7f0fa23',
				'label' => 'Attending Box',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_555c6d9d0fa24',
				'label' => 'Attending Image',
				'name' => 'attending_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_555c6db30fa25',
				'label' => 'Attending Title',
				'name' => 'attending_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555c6ddb0fa26',
				'label' => 'Attending Text',
				'name' => 'attending_text',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_555c6df40fa27',
				'label' => 'Attending Link To Page?',
				'name' => 'attending_link_to_page',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_555c6c8f3fa1e',
				'label' => 'Next Fair',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_555c7cc53fa1f',
				'label' => 'Next Fair Image',
				'name' => 'next_image',
				'type' => 'image',
				'instructions' => 'Preferred size is 709 x 444',
				'column_width' => '',
				'save_format' => 'object',
				'preview_size' => 'home-image',
				'library' => 'all',
			),
			array (
				'key' => 'field_555c42e35acc9',
				'label' => 'Next Fair Title',
				'name' => 'next_title',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_555c3df40fa27',
				'label' => 'Next Fair Link To Page?',
				'name' => 'next_link_to_page',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'page',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),

		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '4',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}




?>